### PR TITLE
CON-4885-supporting-creating-ia-rulesets

### PR DESCRIPTION
**Pull request by barnuri-cp**

### CODE REVIEW

**Comment by barnuri-cp** [comment]
https://dome9-security.atlassian.net/browse/DFT-2055
https://dome9-security.atlassian.net/browse/CON-4885

**Comment by chkp-alexgl** [comment]
@barnuri-cp please, update under docs/ too (with brief explanation, since it might not be obvious/intuitive to an average user)

**Comment by barnuri-cp** [comment]
image

image

@chkp-alexgl  tested in us9

**Review by chkp-alexgl — APPROVED** [review]
LGTM

**Review by chkp-dolevh — APPROVED** [review]

**Pull request merged**
