### PR TITLE
Add missing compute to inbound configuration for AWS security groups

### PR DESCRIPTION
**Pull request by DanielRis**
When running Terraform to update security groups, we did see errors like

```
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Modifying... [id=removed]
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Still modifying... [id=removed, 10s elapsed]
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Still modifying... [id=removed, 20s elapsed]
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Still modifying... [id=removed, 30s elapsed]
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Still modifying... [id=removed, 40s elapsed]
dome9_cloud_security_group_rule.sso-lb-sg_us-west-2: Still modifying... [id=removed, 50s elapsed]
╷
│ Error: FAILED: PUT, https://api.dome9.com/v2/CloudSecurityGroup/<removed>, 400, 400 Bad Request, {"message":"Error converting value \"\" to type 'Falconetix.Model.ScopeElementType'. Path 'services.inbound[0].scope[0].type', line 1, position 54."}
│ 
│   with dome9_cloud_security_group_rule.sso-lb-sg_us-west-2,
│   on main.tf line 152, in resource "dome9_cloud_security_group_rule" "sso-lb-sg_us-west-2":
│  152: resource "dome9_cloud_security_group_rule" "sso-lb-sg_us-west-2" {
│ 
```

After doing lot of debugging, I figured out that the `computed` property of the `inbound` values were missing for AWS security group resources. Internally, the provider then had two map entries for `inbound`, one was empty, the other one contained the actual value. The order was by random? or something i was not able to predict. `outbound` was not affected by this.

With this fix, the `inbound` is now also properly classified as bing optional and computed (because it could be both). Wit this, all my tests are successful.

### CODE REVIEW

**Review by jsojourner11 — APPROVED** [review]

**Review by jsojourner11 — APPROVED** [review]
lgtm

**Comment by DanielRis** [comment]
@jsojourner11  is there anything else missing here? We are constantly run into this issue. I am wondering if nobody else is reporting this. @dolevh-d9

**Comment by jsojourner11** [comment]
> @jsojourner11 is there anything else missing here? We are constantly run into this issue. I am wondering if nobody else is reporting this. @dolevh-d9

Sorry, I am not an approving reviewer, but we are also constantly running into this issue and would greatly appreciate if this got merged

**Comment by chkp-dolevh** [comment]
> > @jsojourner11 is there anything else missing here? We are constantly run into this issue. I am wondering if nobody else is reporting this. @dolevh-d9
> 
> Sorry, I am not an approving reviewer, but we are also constantly running into this issue and would greatly appreciate if this got merged

I'll check this out ASAP

**Comment by DanielRis** [comment]
@dolevh-d9 @itzikYeret is there anything else we could do to get this reviewed and maybe merged/released?

**Review by chkp-yogevk — APPROVED** [review]

**Comment by chkp-dolevh** [comment]
> @dolevh-d9 @itzikYeret is there anything else we could do to get this reviewed and maybe merged/released?

@DanielRis 
I hope that next week we will merge the changes after I have time to look at them in more depth

**Comment by DanielRis** [comment]
@dolevh-d9 any update here?

**Review by chkp-dolevh — APPROVED** [review]

**Pull request merged**
